Serilog:
  Using:
    - Serilog.Sinks.Debug
    - Serilog.Sinks.ApplicationInsights
  Enrich:
    - FromLogContext
  Properties:
    Application: Microservice.DocumentType
  MinimumLevel:
    Default: Information
  WriteTo:
    - Name: Async
      Args:
        configure:
          - Name: Console
            Args:
              theme: Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console
              outputTemplate:
                "[{Application}] [{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}
                <s:{SourceContext}>{NewLine}{Exception}"
